### ISSUE TITLE
Something wrong with Shapely 1.3

### ISSUE THREAD

**Issue by jasonbeverage** [omniscale/imposm#35] opened 2014-01-03 00:56 UTC
Not sure exactly what the problem is but I just installed imposm on a fresh Ubuntu x64 machine and it pulled down Shapely 1.3 from pip.  When I went to import any pbf at all it complains about the enforce_dims_geometry being violated.  Downgrading to Shapely 1.2.14 fixed things for me.  Shapely 1.3 is really new (2 days ago) so it probably hasn't been tested with imposm much if at all.

**Comment by joaoponceleao** [comment] 2015-01-10 13:44
Hi,
Considering we're at impose release 2.6.0 now, what is the current status here. Should we still be pinning the Shapely requirement to < 1.3?

**Comment by joaoponceleao** [comment] 2015-01-10 13:46
Nevermind,
Having update impose just now, I see that the Shapely requirement is now >= 1.5.
This issue should probably be closed now as solved?

**Comment by olt** [comment] 2015-01-10 13:49
It should work with a recent version of Shapely and GEOS. So, I'm closing this.

**Closed by olt** 2015-01-10 13:49 UTC

**Comment by joaoponceleao** [comment] 2015-01-19 12:38
I believe this has to be reopened with a recommendation for `Shapely==1.5.2`. There seem to be issues with 1.5.3.

**Comment by olt** [comment] 2015-01-19 12:46
Could you provide more details?

**Comment by joaoponceleao** [comment] 2015-01-19 12:50
Oh dear... I noticed this a few days ago but am at 1.5.2 now.
Mind you, I'm on a mac, and I believe the 1.5.3 update is mostly about mac-specific bins?
Basically, imposm failed with a series of errors when trying to import. Going back to Shapely==1.5.2 took care of the issue.
I will do a test import soon and get back to you with the error list.

**Comment by joaoponceleao** [comment] 2015-01-19 13:24
Ok. Problem is `ValueError: Null geometry supports no operations`. Here goes the last part of the length shell output with latest Shapely. This is on a mac with postgres running through postgresql-common.

```
[2015-01-19 13:21:16,259] imposm.multipolygon - WARNING - error while building multipolygon:
[2015-01-19 13:21:16,259] imposm.multipolygon - ERROR - Null geometry supports no operations
Traceback (most recent call last):
  File "/Users/joao/.pyenv/versions/imposm/lib/python2.7/site-packages/imposm/multipolygon.py", line 146, in build
    self.build_relation_geometry(rings)
  File "/Users/joao/.pyenv/versions/imposm/lib/python2.7/site-packages/imposm/multipolygon.py", line 221, in build_relation_geometry
    rings.sort(key=lambda x: x.geom.area, reverse=True)
  File "/Users/joao/.pyenv/versions/imposm/lib/python2.7/site-packages/imposm/multipolygon.py", line 221, in <lambda>
    rings.sort(key=lambda x: x.geom.area, reverse=True)
  File "/Users/joao/.pyenv/versions/imposm/lib/python2.7/site-packages/shapely/geometry/base.py", line 397, in area
    return self.impl['area'](self)
  File "/Users/joao/.pyenv/versions/imposm/lib/python2.7/site-packages/shapely/topology.py", line 55, in __call__
    self._validate(this)
  File "/Users/joao/.pyenv/versions/imposm/lib/python2.7/site-packages/shapely/topology.py", line 18, in _validate
    raise ValueError("Null geometry supports no operations")
ValueError: Null geometry supports no operations

[13:21:16] relations: total time 1 s for 383 (365/s)
Assertion failed: (0), function write, file WKBWriter.cpp, line 127.
Assertion failed: (0), function write, file WKBWriter.cpp, line 127.
```

**Comment by joaoponceleao** [comment] 2015-01-19 13:25
PS. I have to quit the terminal to get out. Even a keyboard interrupt won't do any good.

**Comment by olt** [comment] 2015-01-19 14:31
Ok, looks like it is related to the new binary packages for Mac OS X.
See https://github.com/Toblerity/Shapely/issues/224

**Comment by olt** [comment] 2015-01-19 16:41
Shapely 1.5.4 is out and should fix it.

**Comment by joaoponceleao** [comment] 2015-01-19 17:02
Yup. Confirmed, everything is smooth now. Thanks for that.

**Comment by JeongJun-Lee** [comment] 2015-03-31 05:57
Hello, I had a same issue. Please let me know how to downgrade it. Sorry, I am a novice.
